;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Player.Health",NewTagName="Player.OnCurrentHealthChanged")
+GameplayTagList=(Tag="Level.Win",DevComment="")
+GameplayTagList=(Tag="Player.Checkpoint.SetRespawnData",DevComment="")
+GameplayTagList=(Tag="Player.Death",DevComment="")
+GameplayTagList=(Tag="Player.Heal",DevComment="")
+GameplayTagList=(Tag="Player.Respawn.Complete",DevComment="")
+GameplayTagList=(Tag="Score.AdjustScore",DevComment="")
+GameplayTagList=(Tag="UI.Player.HealthUpdated",DevComment="")
+GameplayTagList=(Tag="UI.Score.ScoreUpdated",DevComment="Payload contains the total score. Sent when the player\'s score is updated.")

