;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Level.Win",DevComment="")
+GameplayTagList=(Tag="Player.Death",DevComment="")
+GameplayTagList=(Tag="Player.Health",DevComment="")
+GameplayTagList=(Tag="Player.Pickup.Healing",DevComment="Event for listent to when the player picks up a healing pickup, The payload will send the amount to heal")

